spring.application.name=Backend
spring.security.user.name=root
spring.security.user.password = root

# ===============================
# DATABASE CONFIGURATION
# ===============================
#spring.datasource.url=jdbc:mysql://localhost:3306/NoteHub
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/NoteHub?sslMode=REQUIRED
spring.datasource.username=2XKJ5YuSHwyVmag.root
spring.datasource.password=cjEUkqWWKJuZ768e
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true